data:extend
{
  {
    type = "item",
    name = "sqs-mining-drill",
    icon = "__salvage-quickstart__/graphics/icons/sqs-mining-drill.png",
    icon_size = 32,
    subgroup = "extraction-machine",
    order = "sqs-mining-drill",
    place_result = "sqs-mining-drill",
    stack_size = 1,
  },
  {
    type = "item",
    name = "sqs-furnace",
    icon = "__salvage-quickstart__/graphics/icons/sqs-furnace.png",
    icon_size = 32,
    subgroup = "smelting-machine",
    order = "sqs-furnace",
    place_result = "sqs-furnace",
    stack_size = 1,
  },
  {
    type = "item",
    name = "sqs-roboport",
    icon = "__salvage-quickstart__/graphics/icons/sqs-roboport.png",
    icon_size = 32,
    subgroup = "logistic-network",
    order = "sqs-roboport",
    place_result = "sqs-roboport",
    stack_size = 1,
  },
  {
    type = "item",
    name = "sqs-construction-robot",
    icon = "__salvage-quickstart__/graphics/icons/sqs-construction-robot.png",
    icon_size = 32,
    subgroup = "logistic-network",
    order = "sqs-roboport",
    place_result = "sqs-construction-robot",
    stack_size = 10,
  },
}
